dist: trusty
language: node_js
node_js:
  - "11"
services:
  - mongodb
  - rabbitmq
before_install:
  - echo "install"
  - yarn add global jest  
  - chmod +x ./shells/env-config.sh
  - ./shells/env-config.sh
install:
  - yarn install
before_script:
  - "echo script"
script:
  - yarn lint
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - echo done
